CREATE TABLE public.account (
    account_id bigint NOT NULL,
    balance numeric(19,2),
    number numeric(19,2),
    status boolean,
    type character varying(255),
    customer_id bigint NOT NULL
);

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.customer (
    password character varying(255),
    status boolean,
    customer_id bigint NOT NULL
);


CREATE TABLE public.movement (
    movement_id bigint NOT NULL,
    amount numeric(19,2),
    balance numeric(19,2),
    date timestamp without time zone,
    description character varying(255),
    type character varying(255),
    account_id bigint NOT NULL
);


ALTER TABLE public.movement ALTER COLUMN movement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.person (
    person_id bigint NOT NULL,
    address character varying(255),
    age bigint,
    gender character varying(255),
    id_number bigint,
    name character varying(255),
    phone character varying(255)
);

ALTER TABLE public.person ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO public.account VALUES (2, 100000.00, 4234234.00, true, 'Cuenta Corriente', 1);
INSERT INTO public.account VALUES (1, 131000.00, 1234567820.00, true, 'Cuenta de ahorros', 1);

INSERT INTO public.customer VALUES ('test123', true, 1);

INSERT INTO public.movement VALUES (11, 5000.00, 126000.00, '2022-09-19 00:08:06.912', 'Deposito de 5000', 'Deposito', 1);
INSERT INTO public.movement VALUES (12, 5000.00, 131000.00, '2022-10-18 00:08:08.265', 'Deposito de 5000', 'Deposito', 1);
INSERT INTO public.movement VALUES (13, 5000.00, 136000.00, '2022-10-19 00:22:31.263', 'Deposito de 5000', 'Deposito', 1);
INSERT INTO public.movement VALUES (14, -5000.00, 141000.00, '2022-10-19 00:22:41.35', 'Retiro de 5000', 'Retiro', 1);
INSERT INTO public.movement VALUES (15, -5000.00, 136000.00, '2022-10-19 00:25:35.148', 'Retiro de 5000', 'Retiro', 1);

INSERT INTO public.person VALUES (1, 'Carrera 1', 31, 'Hombre', 1111132, 'Diego Malavera', '3185555555');

SELECT pg_catalog.setval('public.account_account_id_seq', 2, true);

SELECT pg_catalog.setval('public.movement_movement_id_seq', 15, true);

SELECT pg_catalog.setval('public.person_person_id_seq', 1, true);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (customer_id);

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_pkey PRIMARY KEY (movement_id);


ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (person_id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fknnwpo0lfq4xai1rs6887sx02k FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT fkoemeananv9w9qnbcoccbl70a0 FOREIGN KEY (account_id) REFERENCES public.account(account_id);

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT fkqw58igk7s2kunxvf7ns62ktu2 FOREIGN KEY (customer_id) REFERENCES public.person(person_id);
