--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3
-- Dumped by pg_dump version 13.3

-- Started on 2022-10-19 00:30:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 3021 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 201 (class 1259 OID 107060)
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    account_id bigint NOT NULL,
    balance numeric(19,2),
    number numeric(19,2),
    status boolean,
    type character varying(255),
    customer_id bigint NOT NULL
);


--
-- TOC entry 200 (class 1259 OID 107058)
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 107065)
-- Name: customer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer (
    password character varying(255),
    status boolean,
    customer_id bigint NOT NULL
);


--
-- TOC entry 204 (class 1259 OID 107072)
-- Name: movement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movement (
    movement_id bigint NOT NULL,
    amount numeric(19,2),
    balance numeric(19,2),
    date timestamp without time zone,
    description character varying(255),
    type character varying(255),
    account_id bigint NOT NULL
);


--
-- TOC entry 203 (class 1259 OID 107070)
-- Name: movement_movement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movement ALTER COLUMN movement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 107082)
-- Name: person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.person (
    person_id bigint NOT NULL,
    address character varying(255),
    age bigint,
    gender character varying(255),
    id_number bigint,
    name character varying(255),
    phone character varying(255)
);


--
-- TOC entry 205 (class 1259 OID 107080)
-- Name: person_person_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.person ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3010 (class 0 OID 107060)
-- Dependencies: 201
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.account VALUES (2, 100000.00, 4234234.00, true, 'Cuenta Corriente', 1);
INSERT INTO public.account VALUES (1, 131000.00, 1234567820.00, true, 'Cuenta de ahorros', 1);


--
-- TOC entry 3011 (class 0 OID 107065)
-- Dependencies: 202
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.customer VALUES ('test123', true, 1);


--
-- TOC entry 3013 (class 0 OID 107072)
-- Dependencies: 204
-- Data for Name: movement; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.movement VALUES (11, 5000.00, 126000.00, '2022-09-19 00:08:06.912', 'Deposito de 5000', 'Deposito', 1);
INSERT INTO public.movement VALUES (12, 5000.00, 131000.00, '2022-10-18 00:08:08.265', 'Deposito de 5000', 'Deposito', 1);
INSERT INTO public.movement VALUES (13, 5000.00, 136000.00, '2022-10-19 00:22:31.263', 'Deposito de 5000', 'Deposito', 1);
INSERT INTO public.movement VALUES (14, -5000.00, 141000.00, '2022-10-19 00:22:41.35', 'Retiro de 5000', 'Retiro', 1);
INSERT INTO public.movement VALUES (15, -5000.00, 136000.00, '2022-10-19 00:25:35.148', 'Retiro de 5000', 'Retiro', 1);


--
-- TOC entry 3015 (class 0 OID 107082)
-- Dependencies: 206
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.person VALUES (1, 'Carrera 1', 31, 'Hombre', 1111132, 'Diego Malavera', '3185555555');


--
-- TOC entry 3022 (class 0 OID 0)
-- Dependencies: 200
-- Name: account_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.account_account_id_seq', 2, true);


--
-- TOC entry 3023 (class 0 OID 0)
-- Dependencies: 203
-- Name: movement_movement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.movement_movement_id_seq', 15, true);


--
-- TOC entry 3024 (class 0 OID 0)
-- Dependencies: 205
-- Name: person_person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.person_person_id_seq', 1, true);


--
-- TOC entry 2869 (class 2606 OID 107064)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- TOC entry 2871 (class 2606 OID 107069)
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (customer_id);


--
-- TOC entry 2873 (class 2606 OID 107079)
-- Name: movement movement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT movement_pkey PRIMARY KEY (movement_id);


--
-- TOC entry 2875 (class 2606 OID 107089)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (person_id);


--
-- TOC entry 2876 (class 2606 OID 107090)
-- Name: account fknnwpo0lfq4xai1rs6887sx02k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fknnwpo0lfq4xai1rs6887sx02k FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


--
-- TOC entry 2878 (class 2606 OID 107100)
-- Name: movement fkoemeananv9w9qnbcoccbl70a0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT fkoemeananv9w9qnbcoccbl70a0 FOREIGN KEY (account_id) REFERENCES public.account(account_id);


--
-- TOC entry 2877 (class 2606 OID 107095)
-- Name: customer fkqw58igk7s2kunxvf7ns62ktu2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT fkqw58igk7s2kunxvf7ns62ktu2 FOREIGN KEY (customer_id) REFERENCES public.person(person_id);


-- Completed on 2022-10-19 00:30:02

--
-- PostgreSQL database dump complete
--

